# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
os: ubuntu-22.04
apt_packages:
- default-jre # This seems to be ignored
tools:
python: "3.10"
# We can only define the content of the final deployment, if we do the complete build on our own.apt_packages:
# So we need to handle package installation, build start and copying the right files for deployment.
commands:
- pip install -r requirements.txt
- sphinx-build -M simplepdf docs docs/build # Use a different build-folder for a really clean build
- sphinx-build -M html docs docs/_build # HTML latest, because it needs the built PDF files
- mkdir -p _readthedocs/html/
- cp -r docs/_build/html/* _readthedocs/html/